name: Run the unit tests

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install-requirements
      run: |
        pip install -r tests-requirements.txt
        pip install -r requirements.txt
    - name: pytest
      run: |
        pytest -v
      working-directory: ./utils
